apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: repro-app
  namespace: default
spec:
  components:
    - name: my-comp
      type: webservice
      properties:
        image: nginx
      traits:
        - type: configmap-trait
          properties:
            data:
              key1: valueFIXTEST
